### ISSUE TITLE
请问这种方式build之后是一个包还是三个独立分开的？

### ISSUE THREAD

**Issue by KevinBaiSg** [mailzwj/micro_frontend#1]

**Comment by mailzwj** [comment]
这只是个DEMO，todo、myfav、main三个应用build之后需要部署到不同的服务（或在不同的html页面中运行）才能演示主应用加载不同的子应用的效果。所以是需要三个应用分开build，build之后三个独立分开。

**Comment by KevinBaiSg** [comment]
不知道您那边有什么方案可以把这三个整合到一块没？

**Comment by mailzwj** [comment]
微应用的目的就是拆分，把大应用拆分成各个子应用，再通过主应用集成。如果要合到一块儿就没必要做微应用了，直接使用常规的单页面应用实现方案就可以了

**Comment by KevinBaiSg** [comment]
嗯，有道理，不知道现在这种方式适合生产环境用吗？

**Comment by mailzwj** [comment]
适不适合要结合具体的业务来看，但至少方案是可行的。虽然目前微前端还没有完全成熟，也没有相关的最佳实践案例或教程，不过据我所知，已经有基于qiankun的前端微应用产品跑在生产环境了。
